apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tic-tac-toe
  name: tic-tac-toe
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - image: snaruto7/tic-tac-toe:v1
        imagePullPolicy: IfNotPresent
        name: tic-tac-toe
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
