apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tic-tac-toe
  name: tic-tac-toe
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - image: snaruto7/tic-tac-toe:v1
        imagePullPolicy: IfNotPresent
        name: tic-tac-toe
