apiVersion: v1
kind: Service
metadata:
  labels:
    app: tic-tac-toe
  name: tic-tac-toe
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: tic-tac-toe
  type: LoadBalancer

